// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DataBase.Models;

namespace Persistence.DataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IngredientePizza", b =>
                {
                    b.Property<int>("Ingredienteid")
                        .HasColumnType("int");

                    b.Property<int>("Pizzaid")
                        .HasColumnType("int");

                    b.HasKey("Ingredienteid", "Pizzaid");

                    b.HasIndex("Pizzaid");

                    b.ToTable("IngredientePizza");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.DetallePedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PedidoId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("PizzaId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<double>("subTotal")
                        .HasMaxLength(50)
                        .HasColumnType("float");

                    b.Property<int>("tamaño")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("tipo")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PizzaId")
                        .IsUnique();

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.Factura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PedidoId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("formaPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.Ingrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("demora")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fecha")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.Pizza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("precio")
                        .HasMaxLength(50)
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("IngredientePizza", b =>
                {
                    b.HasOne("Persistence.DataBase.Models.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("Ingredienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("Pizzaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.DataBase.Models.DetallePedido", b =>
                {
                    b.HasOne("Persistence.DataBase.Models.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.DataBase.Models.Pizza", "Pizza")
                        .WithOne("DetallePedido")
                        .HasForeignKey("Persistence.DataBase.Models.DetallePedido", "PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.Factura", b =>
                {
                    b.HasOne("Persistence.DataBase.Models.Pedido", "Pedido")
                        .WithOne("Factura")
                        .HasForeignKey("Persistence.DataBase.Models.Factura", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Persistence.DataBase.Models.Pizza", b =>
                {
                    b.Navigation("DetallePedido");
                });
#pragma warning restore 612, 618
        }
    }
}
